#!/bin/bash

set -ex

# Script is assumed in qubes-builderv2 root directory
builder_dir="$(dirname "$0")"

# Component directory is passed as argument
component_dir="$1"
dist="$2"

component_name="$(basename "$component_dir")"

if [ -z "$component_dir" ]; then
    echo "Please provide component directory."
    exit 1
fi

if [ "${component_name#qubes-}" == "${component_name}" ]; then
    echo "Cannot find 'qubes-' suffix. Is it a Qubes OS component?"
    exit 1
fi

if [ -z "$dist" ]; then
    echo "Please provide dist (e.g. host-fc32)."
    exit 1
fi

# Drop qubes- prefix
component_name=${component_name#qubes-}

# Go to builder root directory
cd "$builder_dir"

read -a -r qb_opts <<< echo "${qb_opts}"

# if prep:sources added components list to the config, use that instead
if grep -q '^components:$' builder.yml; then
    # Run all stages
    ./qb "${qb_opts[@]}" -d "${dist}" package all
else
    # Run all stages
    ./qb "${qb_opts[@]}" -c "$component_name" -d "${dist}" package all
fi

mkdir -p artifacts/repository
find artifacts/repository -type f -ls -exec sha1sum {} +
