#!/bin/bash

set -ex

# go to builder main directory
scriptdir="$(readlink -f "$(dirname "$0")")"
builderdir="$(readlink -f "$scriptdir"/..)"
cd "$builderdir"

# shellcheck source=scripts/common
. scripts/common

packages="$(find qubes-packages-mirror-repo/ -type f -regex '.*\(deb\|rpm\|zst\)$' 2>/dev/null)"
if [ -z "$packages" ]; then
    echo "Nothing was built, skipping reproducible stage"
    exit
fi

# we don't show most of repro log, echo some text to prevent Travis-CI timeout
keep_alive &
keep_alive_pid=$!

trap 'exit_ci gitlab-reprotest.log ${keep_alive_pid}' 0 1

YUM="$(/usr/bin/which dnf || true)"
if [ -z "$YUM" ]; then
    YUM="$(/usr/bin/which yum || true)"
fi
APT="$(/usr/bin/which apt-get || true)"

# Ensure to have fuse node
test -c /dev/fuse || mknod -m 666 /dev/fuse c 10 229

# Create artifacts folder to backup only failing tests
mkdir -p "$builderdir/artifacts"

# NOTE: we remove 'domain_host' variation as we execute into a chroot
# for both DEB and RPM based distribution. We remove 'kernel' variation
# for RPM based only as it's not supported. We also remove 'build_path'
# variation only for RPM as they are built using Mock with a constant
# path. See reprotest manual.

if [ "$YUM" ]; then
    # copy qubes-builder packages repo to /tmp/qubes-packages-mirror-repo
    builder_repo_dir="$builderdir/qubes-packages-mirror-repo/$([[ -n ${DIST_DOM0} ]] && echo "dom0-${DIST_DOM0}" || echo "vm-${DISTS_VM}")"
    sudo mkdir -p /tmp/qubes-packages-mirror-repo
    sudo mount --bind "$builder_repo_dir" /tmp/qubes-packages-mirror-repo

    sudo dnf makecache

    # add mockbuild user
    if ! id -u mockbuild; then
        sudo useradd mockbuild
    fi

    SRCRPMS="$(find /tmp/qubes-packages-mirror-repo -type f -name "*.src.rpm")"
    for srcrpm in $SRCRPMS
    do
        job=$(basename "$srcrpm")
        job="${job/.src.rpm/}"
        mkdir -p "$job"
        # shellcheck disable=SC2024
        if sudo reprotest --store-dir "$builderdir/artifacts/$job" --no-clean-on-error \
                --vary=-domain_host,-kernel,-build_path --testbed-build-pre "dnf builddep -y --allowerasing $srcrpm" "$srcrpm" \
                >> gitlab-reprotest.log 2>&1; then
            echo "$job|YES" >> gitlab-reprotest-status.log
        else
            echo "$job|NO" >> gitlab-reprotest-status.log
            exit_code=1
        fi
    done
fi

if [ "$APT" ]; then
    # copy qubes-builder packages repo to /tmp/qubes-repo
    builder_repo_dir="$builderdir/qubes-packages-mirror-repo/$([[ -n ${DIST_DOM0} ]] && echo "dom0-${DIST_DOM0}" || echo "vm-${DISTS_VM}")"
    sudo mkdir -p /tmp/qubes-deb
    sudo mount --bind "$builder_repo_dir" /tmp/qubes-deb

    # update qubes-builder and Qubes repositories as we brought packages with artifacts
    sudo apt-get update

    CONTROLS="$(find /tmp/qubes-deb -type f -name "*.dsc")"
    for control in $CONTROLS
    do
        job=$(basename "$control")
        job="${job/.dsc/}"
        mkdir -p "$job"
        # shellcheck disable=SC2024
        if sudo reprotest --store-dir "$builderdir/artifacts/$job" --no-clean-on-error \
                --vary=-domain_host --testbed-build-pre "apt-get -y --no-install-recommends build-dep $control" "$control" \
                >> gitlab-reprotest.log 2>&1; then
            echo "$job|YES" >> gitlab-reprotest-status.log
        else
            echo "$job|NO" >> gitlab-reprotest-status.log
            exit_code=1
        fi
    done
fi

# Display results summary
{ echo; printf "%0.s=" {1..72}; } >> gitlab-reprotest.log
column -t gitlab-reprotest-status.log -s'|' --table-columns COMPONENT,REPRODUCIBLE >> gitlab-reprotest.log || true
exit $exit_code
